import type { Metadata } from "next";
import { Poppins, Modak } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const modak = Modak ({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-modak',
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Expiravoid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <html lang="en">
        <body
          className={`${poppins.variable} ${modak.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
